"""
031+01.py
=========

GRAPH + PYBULLET MACHINING EXPERIMENT
--------------------------------------

Goal
----
Combine the two ideas:

    1. GEOMETRY GRAPH
       determines material removal / cutting area

    2. CUTTING MODEL
       converts cutting area into an estimated cutting force

    3. PYBULLET
       represents the machine mechanically:
           - workpiece
           - cutter
           - motion
           - contact
           - force vector

The important conceptual separation is:

    geometry  ->  cutting area
                    |
                    v
                cutting model
                    |
                    v
             cutting force vector
                    |
                    v
                 PyBullet

PyBullet itself is NOT being asked to calculate metal cutting
physics. It receives the force generated by our cutting model.

This is an experimental model, NOT an engineering-grade
machining calculator.

Dependencies
------------

    pip install numpy matplotlib pybullet

Run:

    python "031+01.py"
"""

import math
import time

import numpy as np
import matplotlib.pyplot as plt

import pybullet as p
import pybullet_data


# ============================================================
# PARAMETERS
# ============================================================

MATERIAL = "AISI 1040"

# Initial stock
STOCK_DIAMETER_MM = 20.0
STOCK_LENGTH_MM = 80.0

# HSS tool
TOOL_SIZE_MM = 10.0

# Machining
DEPTH_OF_CUT_MM = 2.0
FEED_MM_REV = 0.10
CUTTING_SPEED_M_MIN = 20.0

# Simplified specific cutting force.
#
# IMPORTANT:
# This is an illustrative value.
# Real Kc depends on chip thickness, rake angle,
# material condition, tool geometry, etc.
KC_N_MM2 = 1500.0

# Simulation scale.
# PyBullet works naturally in meters.
MM = 0.001

# Number of profile points
PROFILE_POINTS = 500


# ============================================================
# UNIT CONVERSION
# ============================================================

def mm(value):
    return value * MM


# ============================================================
# MACHINING EQUATIONS
# ============================================================

def rpm_from_cutting_speed(speed_m_min, diameter_mm):
    """
    Vc = pi * D * N / 1000

    N = 1000 * Vc / (pi * D)
    """

    if diameter_mm <= 0:
        return 0.0

    return (
        1000.0
        * speed_m_min
        / (math.pi * diameter_mm)
    )


def feed_velocity(feed_mm_rev, rpm):
    """
    Feed velocity in mm/min.
    """

    return feed_mm_rev * rpm


def chip_area(depth_mm, feed_mm_rev):
    """
    First approximation:

        Ac = depth * feed

    [mm²]
    """

    return max(depth_mm, 0.0) * max(feed_mm_rev, 0.0)


def cutting_force(area_mm2, kc_n_mm2):
    """
    Simplified cutting-force model:

        Fc = Kc * Ac

    [N]
    """

    return area_mm2 * kc_n_mm2


def torque(force_n, diameter_mm):
    """
    T = F * radius

    [N*m]
    """

    return force_n * (diameter_mm / 2.0) / 1000.0


def power(force_n, cutting_speed_m_min):
    """
    P = F * V

    [W]
    """

    velocity_m_s = cutting_speed_m_min / 60.0

    return force_n * velocity_m_s


# ============================================================
# 2D GRAPH / PROFILE
# ============================================================

class WorkpieceGraph:

    def __init__(
        self,
        diameter_mm=STOCK_DIAMETER_MM,
        length_mm=STOCK_LENGTH_MM,
    ):

        self.diameter_mm = diameter_mm
        self.length_mm = length_mm

        self.z = np.linspace(
            0,
            length_mm,
            PROFILE_POINTS,
        )

        self.radius = np.full_like(
            self.z,
            diameter_mm / 2.0,
        )

    def remove_material(
        self,
        z_start_mm,
        z_end_mm,
        depth_mm,
    ):
        """
        Remove a cylindrical layer from the graph.

        This is our first simple Boolean-like operation.

        Later this can be replaced with actual polygon/mesh
        intersection.
        """

        mask = (
            (self.z >= z_start_mm)
            &
            (self.z <= z_end_mm)
        )

        new_radius = (
            self.radius[mask]
            - depth_mm
        )

        self.radius[mask] = np.maximum(
            new_radius,
            0.05,
        )

    def final_diameter(self):
        return np.min(self.radius) * 2.0


# ============================================================
# CUTTING MODEL
# ============================================================

class CuttingModel:

    def __init__(self):

        self.depth_mm = DEPTH_OF_CUT_MM
        self.feed_mm_rev = FEED_MM_REV
        self.speed_m_min = CUTTING_SPEED_M_MIN
        self.kc = KC_N_MM2

    def calculate(self, diameter_mm):

        area = chip_area(
            self.depth_mm,
            self.feed_mm_rev,
        )

        force = cutting_force(
            area,
            self.kc,
        )

        rpm = rpm_from_cutting_speed(
            self.speed_m_min,
            diameter_mm,
        )

        feed_speed = feed_velocity(
            self.feed_mm_rev,
            rpm,
        )

        T = torque(
            force,
            diameter_mm,
        )

        P = power(
            force,
            self.speed_m_min,
        )

        return {
            "area_mm2": area,
            "force_N": force,
            "rpm": rpm,
            "feed_mm_min": feed_speed,
            "torque_Nm": T,
            "power_W": P,
        }


# ============================================================
# PYBULLET MACHINE
# ============================================================

class PyBulletLathe:

    def __init__(self):

        self.client = p.connect(p.GUI)

        p.setAdditionalSearchPath(
            pybullet_data.getDataPath()
        )

        p.resetSimulation()

        p.setGravity(
            0,
            0,
            0,
        )

        p.setTimeStep(
            1.0 / 240.0
        )

        # ----------------------------------------------------
        # Coordinate system
        #
        # X = spindle / workpiece axis
        # Y/Z = radial directions
        # ----------------------------------------------------

        self.workpiece_length = mm(
            STOCK_LENGTH_MM
        )

        self.workpiece_radius = mm(
            STOCK_DIAMETER_MM / 2.0
        )

        # ----------------------------------------------------
        # Ground / machine base
        # ----------------------------------------------------

        ground_shape = p.createCollisionShape(
            p.GEOM_BOX,
            halfExtents=[
                0.06,
                0.06,
                0.005,
            ],
        )

        self.ground = p.createMultiBody(
            baseMass=0,
            baseCollisionShapeIndex=ground_shape,
            basePosition=[
                0,
                0,
                -0.02,
            ],
        )

        # ----------------------------------------------------
        # Workpiece
        # ----------------------------------------------------

        workpiece_collision = p.createCollisionShape(
            p.GEOM_CYLINDER,
            radius=self.workpiece_radius,
            height=self.workpiece_length,
        )

        workpiece_visual = p.createVisualShape(
            p.GEOM_CYLINDER,
            radius=self.workpiece_radius,
            length=self.workpiece_length,
            rgbaColor=[
                0.55,
                0.55,
                0.60,
                1,
            ],
        )

        self.workpiece = p.createMultiBody(
            baseMass=2.0,
            baseCollisionShapeIndex=workpiece_collision,
            baseVisualShapeIndex=workpiece_visual,
            basePosition=[
                0,
                0,
                0,
            ],
            baseOrientation=p.getQuaternionFromEuler(
                [0, math.pi / 2, 0]
            ),
        )

        # ----------------------------------------------------
        # Tool
        # ----------------------------------------------------

        tool_half = mm(
            TOOL_SIZE_MM / 2
        )

        tool_collision = p.createCollisionShape(
            p.GEOM_BOX,
            halfExtents=[
                tool_half,
                tool_half,
                tool_half,
            ],
        )

        tool_visual = p.createVisualShape(
            p.GEOM_BOX,
            halfExtents=[
                tool_half,
                tool_half,
                tool_half,
            ],
            rgbaColor=[
                0.85,
                0.55,
                0.10,
                1,
            ],
        )

        # Tool is intentionally positioned near the stock.
        self.tool_position = [
            0,
            self.workpiece_radius
            + mm(TOOL_SIZE_MM / 2)
            - mm(DEPTH_OF_CUT_MM),
            0,
        ]

        self.tool = p.createMultiBody(
            baseMass=0.5,
            baseCollisionShapeIndex=tool_collision,
            baseVisualShapeIndex=tool_visual,
            basePosition=self.tool_position,
        )

        # ----------------------------------------------------
        # Camera
        # ----------------------------------------------------

        p.resetDebugVisualizerCamera(
            cameraDistance=0.12,
            cameraYaw=45,
            cameraPitch=-25,
            cameraTargetPosition=[
                0,
                0,
                0,
            ],
        )

        # ----------------------------------------------------
        # Force visualization
        # ----------------------------------------------------

        self.force_debug_id = -1

    # ========================================================
    # FORCE VECTOR
    # ========================================================

    def draw_force_vector(
        self,
        force_n,
    ):

        # The visual arrow is scaled because real machining
        # forces are huge compared with our millimeter model.

        visualization_scale = 0.000005

        arrow_length = (
            force_n
            * visualization_scale
        )

        if arrow_length < 0.001:
            arrow_length = 0.001

        start = np.array(
            self.tool_position,
            dtype=float,
        )

        # Tangential cutting-force direction.
        #
        # For this simplified stationary visualization,
        # use +X as the cutting-force direction.

        direction = np.array(
            [1.0, 0.0, 0.0]
        )

        end = (
            start
            + direction * arrow_length
        )

        self.force_debug_id = p.addUserDebugLine(
            start,
            end.tolist(),
            lineColorRGB=[
                1,
                0,
                0,
            ],
            lineWidth=4,
            lifeTime=0.0,
            replaceItemUniqueId=(
                self.force_debug_id
                if self.force_debug_id >= 0
                else -1
            ),
        )

    # ========================================================
    # APPLY FORCE
    # ========================================================

    def apply_cutting_force(
        self,
        force_n,
    ):
        """
        Apply cutting force to the tool.

        PyBullet receives the force as a vector.

        Later we can apply:
            - tangential force
            - radial force
            - axial force

        separately.
        """

        force_vector = [
            force_n,
            0,
            0,
        ]

        p.applyExternalForce(
            objectUniqueId=self.tool,
            linkIndex=-1,
            forceObj=force_vector,
            posObj=self.tool_position,
            flags=p.WORLD_FRAME,
        )

    # ========================================================
    # STEP
    # ========================================================

    def step(
        self,
        force_n,
    ):

        self.apply_cutting_force(
            force_n
        )

        self.draw_force_vector(
            force_n
        )

        p.stepSimulation()


# ============================================================
# VISUAL GRAPH
# ============================================================

class GraphDisplay:

    def __init__(self):

        plt.ion()

        self.fig, self.ax = plt.subplots(
            figsize=(9, 5)
        )

    def draw(
        self,
        graph,
        result,
    ):

        self.ax.clear()

        # Current workpiece
        self.ax.plot(
            graph.z,
            graph.radius,
            color="black",
            linewidth=2,
            label="Workpiece",
        )

        # Center line
        self.ax.axhline(
            0,
            color="gray",
            linewidth=1,
        )

        # Cutting region
        z0 = 20.0
        z1 = 60.0

        mask = (
            (graph.z >= z0)
            &
            (graph.z <= z1)
        )

        original_radius = (
            STOCK_DIAMETER_MM / 2
        )

        self.ax.fill_between(
            graph.z[mask],
            graph.radius[mask],
            original_radius,
            color="red",
            alpha=0.25,
            label="Removed material",
        )

        # ----------------------------------------------------
        # Information
        # ----------------------------------------------------

        text = (
            f"{MATERIAL}\n\n"
            f"Stock Ø: {STOCK_DIAMETER_MM:.1f} mm\n"
            f"Current Ø: "
            f"{graph.final_diameter():.2f} mm\n\n"
            f"Depth: "
            f"{DEPTH_OF_CUT_MM:.2f} mm\n"
            f"Feed: "
            f"{FEED_MM_REV:.3f} mm/rev\n\n"
            f"Cutting area: "
            f"{result['area_mm2']:.3f} mm²\n"
            f"Cutting force: "
            f"{result['force_N']:.1f} N\n"
            f"Torque: "
            f"{result['torque_Nm']:.3f} N·m\n"
            f"Power: "
            f"{result['power_W']:.1f} W\n\n"
            f"Cutting speed: "
            f"{CUTTING_SPEED_M_MIN:.1f} m/min\n"
            f"RPM: "
            f"{result['rpm']:.1f}\n"
            f"Feed velocity: "
            f"{result['feed_mm_min']:.2f} mm/min"
        )

        self.ax.text(
            1.02,
            0.98,
            text,
            transform=self.ax.transAxes,
            verticalalignment="top",
            family="monospace",
            fontsize=10,
        )

        self.ax.set_title(
            "031+01 — Graph + Cutting Force + PyBullet"
        )

        self.ax.set_xlabel(
            "Z position [mm]"
        )

        self.ax.set_ylabel(
            "Radius [mm]"
        )

        self.ax.grid(
            alpha=0.25
        )

        self.ax.set_xlim(
            0,
            STOCK_LENGTH_MM
        )

        self.ax.set_ylim(
            -1,
            STOCK_DIAMETER_MM / 2 + 3
        )

        self.ax.legend()

        self.fig.canvas.draw()
        self.fig.canvas.flush_events()


# ============================================================
# MAIN SIMULATION
# ============================================================

def main():

    print()
    print("=" * 65)
    print("031+01 — GRAPH + PYBULLET MACHINING EXPERIMENT")
    print("=" * 65)

    graph = WorkpieceGraph()

    cutting = CuttingModel()

    bullet = PyBulletLathe()

    display = GraphDisplay()

    # --------------------------------------------------------
    # Initial calculation
    # --------------------------------------------------------

    result = cutting.calculate(
        STOCK_DIAMETER_MM
    )

    print()
    print("Initial machining state:")
    print(
        f"  Material:       {MATERIAL}"
    )
    print(
        f"  Stock diameter: {STOCK_DIAMETER_MM:.2f} mm"
    )
    print(
        f"  Cutting area:   {result['area_mm2']:.3f} mm²"
    )
    print(
        f"  Cutting force:  {result['force_N']:.1f} N"
    )
    print(
        f"  RPM:            {result['rpm']:.1f}"
    )
    print(
        f"  Torque:         {result['torque_Nm']:.3f} N*m"
    )
    print(
        f"  Power:          {result['power_W']:.1f} W"
    )

    # --------------------------------------------------------
    # Simulate progressive cut
    # --------------------------------------------------------

    for step in range(200):

        # Slowly move through the workpiece.
        z_start = 20.0
        z_end = (
            z_start
            + 40.0
            * step
            / 199.0
        )

        # Update geometry.
        graph.remove_material(
            z_start,
            z_end,
            DEPTH_OF_CUT_MM,
        )

        # Current diameter determines RPM.
        current_diameter = max(
            graph.final_diameter(),
            0.1,
        )

        result = cutting.calculate(
            current_diameter
        )

        # ----------------------------------------------------
        # PyBullet force
        # ----------------------------------------------------

        bullet.step(
            result["force_N"]
        )

        # ----------------------------------------------------
        # Graph visualization
        # ----------------------------------------------------

        display.draw(
            graph,
            result,
        )

        time.sleep(
            0.02
        )

    print()
    print("=" * 65)
    print("FINAL STATE")
    print("=" * 65)

    print(
        f"Final diameter: "
        f"{graph.final_diameter():.3f} mm"
    )

    print(
        f"Final RPM: "
        f"{result['rpm']:.1f}"
    )

    print(
        f"Cutting force: "
        f"{result['force_N']:.1f} N"
    )

    print()
    print(
        "Close the PyBullet and Matplotlib windows to exit."
    )

    # Keep PyBullet alive.
    while p.isConnected():

        p.stepSimulation()

        if not plt.fignum_exists(
            display.fig.number
        ):
            break

        plt.pause(0.01)

    if p.isConnected():
        p.disconnect()


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()
